[project]
name = "diploma"
version = "0.1.0"
description = "Add your description here"
#readme = "README.md"
authors = [
    { name = "Irbis174", email = "matvey.golovkin@mail.ru" }
]
requires-python = ">=3.13"

dependencies = [
    "backend",
    "frontend",
]

[tool.uv.workspace]
members = ["packages/backend", "packages/frontend"]

[tool.uv.sources]
backend = { workspace = true }
frontend = { workspace = true }