path: F:\dataset_diploma
train: train/images
val: val/images
test: test/images

nc: 1
names: ['Gun']


nc: 1
names: ['Gun']

roboflow:
  workspace: [
    ali-yvvte, 
    saad-salman-xwffp,
    meeth4399-gmail-com,
    phillip-lavrador,
    hammad-musaddiq,
    test-mavenir,
    platinum-pythons,
    rescuetrektrainingimages,
    proyecto-p4lkf,
    abdullahinur-abdullahi-xl888
  ]
  project: [
    self-collected-1b1c8, 
    dataset_7,
    weapon1-qlmvy,
    clips-ifysi,
    new-data-for-mulhim,
    weapondata,
    ai-weapons,
    rescuetrek,
    pistolas-mqk5c,
    firearm-detection-q2dp2
  ]
  version: 1
  license: CC BY 4.0
  url: [
    https://universe.roboflow.com/ali-yvvte/self-collected-1b1c8/dataset/1,
    https://universe.roboflow.com/saad-salman-xwffp/dataset_7/dataset/1,
    https://universe.roboflow.com/meeth4399-gmail-com/weapon1-qlmvy/dataset/2,
    https://universe.roboflow.com/phillip-lavrador/clips-ifysi/dataset/2,
    https://universe.roboflow.com/hammad-musaddiq/new-data-for-mulhim/dataset/15,
    https://universe.roboflow.com/test-mavenir/weapondata/dataset/3,
    https://universe.roboflow.com/platinum-pythons/ai-weapons/dataset/40,
    https://universe.roboflow.com/rescuetrektrainingimages/rescuetrek/dataset/2,
    https://universe.roboflow.com/proyecto-p4lkf/pistolas-mqk5c/dataset/2,
    https://universe.roboflow.com/abdullahinur-abdullahi-xl888/firearm-detection-q2dp2/dataset/1
  ]